<option  value="SOLUTION">SOLUTION</option>
<option  value="CAPSULE">CAPSULE</option>
<option  value="TABLET">TABLET</option>
<option  value="KIT">KIT</option>
<option  value="INJECTION">INJECTION</option>
<option  value="POWDER">POWDER</option>
<option  value="GRANULE">GRANULE</option>
<option  value="OINTMENT">OINTMENT</option>
<option  value="SUPPOSITORY">SUPPOSITORY</option>
<option  value="LOTION">LOTION</option>
<option  value="GEL">GEL</option>
<option  value="CREAM">CREAM</option>
<option  value="SUSPENSION">SUSPENSION</option>
<option  value="INHALANT">INHALANT</option>
<option  value="RING">RING</option>
<option  value="SUSPENSION/ DROPS">SUSPENSION/ DROPS</option>
<option  value="SOLUTION/ DROPS">SOLUTION/ DROPS</option>
<option  value="IMPLANT">IMPLANT</option>
<option  value="LIQUID">LIQUID</option>
<option  value="INTRAUTERINE DEVICE">INTRAUTERINE DEVICE</option>
<option  value="TAPE">TAPE</option>
<option  value="EMULSION">EMULSION</option>
<option  value="LOZENGE">LOZENGE</option>
<option  value="AEROSOL">AEROSOL</option>
<option  value="MOUTHWASH">MOUTHWASH</option>
<option  value="SYRUP">SYRUP</option>
<option  value="SPRAY">SPRAY</option>
<option  value="CONCENTRATE">CONCENTRATE</option>
<option  value="PILL">PILL</option>
<option  value="PATCH">PATCH</option>
<option  value="SHAMPOO">SHAMPOO</option>
<option  value="ENEMA">ENEMA</option>
<option  value="RINSE">RINSE</option>
<option  value="ELIXIR">ELIXIR</option>
<option  value="PASTE">PASTE</option>
<option  value="CLOTH">CLOTH</option>
<option  value="DOUCHE">DOUCHE</option>
<option  value="SOAP">SOAP</option>
<option  value="INSERT">INSERT</option>
<option  value="STICK">STICK</option>
<option  value="PELLET">PELLET</option>
<option  value="IRRIGANT">IRRIGANT</option>
<option  value="JELLY">JELLY</option>
<option  value="OIL">OIL</option>
<option  value="SWAB">SWAB</option>
<option  value="DISC">DISC</option>
<option  value="STRIP">STRIP</option>
<option  value="SALVE">SALVE</option>
<option  value="PLASTER">PLASTER</option>
<option  value="EXTRACT">EXTRACT</option>
<option  value="DRESSING">DRESSING</option>
<option  value="SPONGE">SPONGE</option>
<option  value="TINCTURE">TINCTURE</option>
<option  value="FOR SUSPENSION">FOR SUSPENSION</option>
<option  value="GAS">GAS</option>
<option  value="LIPSTICK">LIPSTICK</option>
<option  value="LOTION/SHAMPOO">LOTION/SHAMPOO</option>
<option  value="PASTILLE">PASTILLE</option>
<option  value="FILM">FILM</option>
<option  value="LINIMENT">LINIMENT</option>
<option  value="WAFER">WAFER</option>
<option  value="FOR SOLUTION">FOR SOLUTION</option>
<option  value="POULTICE">POULTICE</option>
<option  value="CRYSTAL">CRYSTAL</option>
<option  value="CELLULAR SHEET">CELLULAR SHEET</option>
<option  value="GLOBULE">GLOBULE</option>
<option  value="INJECTABLE FOAM">INJECTABLE FOAM</option>